package com.qx.model;
// default package
// Generated 2015-11-8 22:30:09 by Hibernate Tools 3.4.0.CR1

/**
 * Baseproperty generated by hbm2java
 */
public class Baseproperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer baseId;
	private String baseName;
	private java.lang.Integer baseStatus;
    private String baseType;
    private String baseShowname;
    
	public String getBaseShowname() {
		return baseShowname;
	}

	public void setBaseShowname(String baseShowname) {
		this.baseShowname = baseShowname;
	}

	public String getBaseType() {
		return baseType;
	}

	public void setBaseType(String baseType) {
		this.baseType = baseType;
	}

	public Baseproperty() {
	}

	public Baseproperty(String baseName, java.lang.Integer baseStatus) {
		this.baseName = baseName;
		this.baseStatus = baseStatus;
	}

	public Integer getBaseId() {
		return this.baseId;
	}

	public void setBaseId(Integer baseId) {
		this.baseId = baseId;
	}

	public String getBaseName() {
		return this.baseName;
	}

	public void setBaseName(String baseName) {
		this.baseName = baseName;
	}

	public java.lang.Integer getBaseStatus() {
		return this.baseStatus;
	}

	public void setBaseStatus(java.lang.Integer baseStatus) {
		this.baseStatus = baseStatus;
	}

}
