package com.qx.model;

import java.util.Date;

// default package
// Generated 2015-11-8 22:30:09 by Hibernate Tools 3.4.0.CR1

/**
 * Shop generated by hbm2java
 */
public class Shop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer shopId;
	private String shopName;
	private String shopPhone;
	private String shopPeople;
	private Date date;
	private String shopWeixin;
	private Integer shopStatus;

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getShopPeople() {
		return shopPeople;
	}

	public void setShopPeople(String shopPeople) {
		this.shopPeople = shopPeople;
	}

	public Shop() {
	}

	public Shop(String shopName, String shopPhone, String shopWeixin,
			Integer shopStatus) {
		this.shopName = shopName;
		this.shopPhone = shopPhone;
		this.shopWeixin = shopWeixin;
		this.shopStatus = shopStatus;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopPhone() {
		return this.shopPhone;
	}

	public void setShopPhone(String shopPhone) {
		this.shopPhone = shopPhone;
	}

	public String getShopWeixin() {
		return this.shopWeixin;
	}

	public void setShopWeixin(String shopWeixin) {
		this.shopWeixin = shopWeixin;
	}

	public Integer getShopStatus() {
		return shopStatus;
	}

	public void setShopStatus(Integer shopStatus) {
		this.shopStatus = shopStatus;
	}

	@Override
	public String toString() {
		return "Shop [shopId=" + shopId + ", shopName=" + shopName
				+ ", shopPhone=" + shopPhone + ", shopPeople=" + shopPeople
				+ ", date=" + date + ", shopWeixin=" + shopWeixin
				+ ", shopStatus=" + shopStatus + "]";
	}

	

}
