package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * SubOrderinfo generated by hbm2java
 */
@JsonIgnoreProperties(value={"goodsinfo","goodsPrice","orderstatuses"}) 
public class SubOrderinfo implements java.io.Serializable {

	private Integer subOrderId;
	private Goodsinfo goodsinfo;
	private Shopgoods shopgoods;
	private Integer goodsId;
	private Orderinfo orderinfo;
	private int goodsNum;
	private BigDecimal goodsPrice;
	private String remark;

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	public SubOrderinfo() {
	}

	public SubOrderinfo(Goodsinfo goodsinfo, Orderinfo orderinfo, int goodsNum) {
		this.goodsinfo = goodsinfo;
		this.orderinfo = orderinfo;
		this.goodsNum = goodsNum;
	}

	public SubOrderinfo(Goodsinfo goodsinfo, Orderinfo orderinfo, int goodsNum,
			BigDecimal goodsPrice) {
		this.goodsinfo = goodsinfo;
		this.orderinfo = orderinfo;
		this.goodsNum = goodsNum;
		this.goodsPrice = goodsPrice;
	}

	public Integer getSubOrderId() {
		return this.subOrderId;
	}

	public void setSubOrderId(Integer subOrderId) {
		this.subOrderId = subOrderId;
	}

	public Goodsinfo getGoodsinfo() {
		return this.goodsinfo;
	}

	public void setGoodsinfo(Goodsinfo goodsinfo) {
		this.goodsinfo = goodsinfo;
	}

	public Orderinfo getOrderinfo() {
		return this.orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public int getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(int goodsNum) {
		this.goodsNum = goodsNum;
	}

	public BigDecimal getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public Shopgoods getShopgoods() {
		return shopgoods;
	}

	public void setShopgoods(Shopgoods shopgoods) {
		this.shopgoods = shopgoods;
	}

	@Override
	public String toString() {
		return "SubOrderinfo [subOrderId=" + subOrderId + ", goodsinfo="
				+ goodsinfo + ", shopgoods=" + shopgoods + ", goodsId="
				+ goodsId + ", goodsNum="
				+ goodsNum + ", goodsPrice=" + goodsPrice + ", remark="
				+ remark + "]";
	}

	

}
